name: Lint before merged pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [13.x]
    step:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, test
      run: |
        npm ci
        npm run lint
      env:
        CI: true
